### ISSUE TITLE
Adding docker-compose.yml file

### ISSUE THREAD

**Issue by HassanKanj** [DevCBeirut/api.devalopers#1]
I am thinking to add a docker-compose.yml to the project which includes the used service(s) (e.g Mongo,...), This can provide another alternative for contributors to easily deploy the project locally.

Let me know what you think @salahawad

**Comment by salahawad** [comment]
it would be great sure

**Comment by salahawad** [comment]
https://github.com/DevCBeirut/api.devalopers/tree/salahdev
